const CONNECTION_EVENT = 'CONNECTION_EVENT'

const MAPPER_SEND_DATA_EVENT = 'MAPPER_SEND_DATA_EVENT'
const MAPPER_RECEIVE_DATA_EVENT = 'MAPPER_RECEIVE_DATA_EVENT'

const REDUCER_SEND_DATA_EVENT = 'REDUCER_SEND_DATA_EVENT'
const REDUCER_RECEIVE_DATA_EVENT = 'REDUCER_RECEIVE_DATA_EVENT'

module.exports = {
  CONNECTION_EVENT,

  MAPPER_SEND_DATA_EVENT,
  MAPPER_RECEIVE_DATA_EVENT,

  REDUCER_SEND_DATA_EVENT,
  REDUCER_RECEIVE_DATA_EVENT,
}
